/*
 *
 * CatalogPage constants
 *
 */

export const REQUESTED_CATALOGTABLE = 'app/CatalogPage/REQUESTED_CATALOGTABLE';
export const REQUESTED_CATALOGTABLE_SUCCEEDED =
  'app/CatalogPage/REQUESTED_CATALOGTABLE_SUCCEEDED';
export const REQUESTED_CATALOGTABLE_FAILED =
  'app/CatalogPage/REQUESTED_CATALOGTABLE_FAILED';
export const FETCHED_CATALOGTABLE = 'app/CatalogPage/FETCHED_CATALOGTABLE';
