/*
 *
 * CatalogPage constants
 *
 */

export const REQUESTED_POSITIONSTABLE =
  'app/CatalogPage/REQUESTED_POSITIONSTABLE';
export const REQUESTED_POSITIONSTABLE_SUCCEEDED =
  'app/CatalogPage/REQUESTED_POSITIONSTABLE_SUCCEEDED';
export const REQUESTED_POSITIONSTABLE_FAILED =
  'app/CatalogPage/REQUESTED_POSITIONSTABLE_FAILED';
export const FETCHED_POSITIONSTABLE = 'app/CatalogPage/FETCHED_POSITIONSTABLE';
